"""FK-target indexes and thread_decisions badge-count composites

Revision ID: 0027
Revises: 0026
Create Date: 2026-09-02 00:00:00.000000

Eighteen FK columns carry an ondelete rule but no index on the referencing
side (measured by cross-checking every model Index/UniqueConstraint/PK
against every alembic create_index/create_unique_constraint/create_table
constraint across alembic/versions/ — issue #25 P1); every user-delete,
agent-delete or thread_decision-delete that cascades through one of these
walks a full table scan on the child instead of an index lookup.
thread_decisions also gets two composite indexes on (agent_a, outcome) and
(agent_b, outcome) — AgentBadgeMiddleware (src/main.py) runs one COUNT per
side per agent per request; measured ~129x speedup at the original audit.

Hand-written, not autogenerated: the ORM/alembic drift already present in
this schema (ten FK columns are indexed only by alembic DDL with no matching
model Index/UniqueConstraint) would make `alembic revision --autogenerate`
try to drop those pre-existing indexes.

Every op.create_index/op.drop_index call below is written out literally, one
name per call (NOT looped over a tuple):
tests/unit/test_migration_checks.py's PLANNED_OBJECTS drift guard finds
index names with the regex `create_index\\(\\s*\\n?\\s*"([^"]+)"`, which only
matches a literal string in the call's first-argument position. A loop like
`for name, table, cols in _INDEXES: op.create_index(name, table, cols)`
makes the guard find zero names and pass vacuously — silently disabling the
one check that would catch a future PLANNED_OBJECTS/migration-file drift
here (verified: sabotaging 5 of the 20 PLANNED_OBJECTS entries with the loop
form still passes the drift guard; with the literal calls below it correctly
fails).

Downgrade is idempotent (if_exists) per the branch convention (0022+).
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0027"
down_revision: Union[str, None] = "0026"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index("ix_access_allowlist_added_by_user_id", "access_allowlist", ["added_by_user_id"])
    op.create_index("ix_agent_delegates_user_id", "agent_delegates", ["user_id"])
    op.create_index("ix_agent_delegates_invitation_id", "agent_delegates", ["invitation_id"])
    op.create_index("ix_agents_approved_by", "agents", ["approved_by"])
    op.create_index("ix_cohort_audit_events_actor_id", "cohort_audit_events", ["actor_id"])
    op.create_index("ix_cohort_memberships_added_by", "cohort_memberships", ["added_by"])
    op.create_index("ix_cohorts_created_by", "cohorts", ["created_by"])
    op.create_index(
        "ix_delegate_invitations_invited_by_user_id", "delegate_invitations", ["invited_by_user_id"]
    )
    op.create_index(
        "ix_delegate_invitations_accepted_by_user_id", "delegate_invitations", ["accepted_by_user_id"]
    )
    op.create_index(
        "ix_email_notifications_thread_decision_id", "email_notifications", ["thread_decision_id"]
    )
    op.create_index(
        "ix_email_notifications_agent_registry_id", "email_notifications", ["agent_registry_id"]
    )
    op.create_index("ix_private_channel_members_user_id", "private_channel_members", ["user_id"])
    op.create_index(
        "ix_private_channel_members_added_by_user_id",
        "private_channel_members",
        ["added_by_user_id"],
    )
    op.create_index(
        "ix_profile_revisions_changed_by_user_id", "profile_revisions", ["changed_by_user_id"]
    )
    op.create_index("ix_proposal_reviews_user_id", "proposal_reviews", ["user_id"])
    op.create_index("ix_proposal_reviews_delegate_user_id", "proposal_reviews", ["delegate_user_id"])
    op.create_index(
        "ix_proposal_reviews_reviewed_by_user_id", "proposal_reviews", ["reviewed_by_user_id"]
    )
    op.create_index(
        "ix_slack_app_provisions_agent_registry_id", "slack_app_provisions", ["agent_registry_id"]
    )
    op.create_index("ix_thread_decisions_agent_a_outcome", "thread_decisions", ["agent_a", "outcome"])
    op.create_index("ix_thread_decisions_agent_b_outcome", "thread_decisions", ["agent_b", "outcome"])


def downgrade() -> None:
    op.drop_index("ix_thread_decisions_agent_b_outcome", table_name="thread_decisions", if_exists=True)
    op.drop_index("ix_thread_decisions_agent_a_outcome", table_name="thread_decisions", if_exists=True)
    op.drop_index(
        "ix_slack_app_provisions_agent_registry_id",
        table_name="slack_app_provisions",
        if_exists=True,
    )
    op.drop_index(
        "ix_proposal_reviews_reviewed_by_user_id", table_name="proposal_reviews", if_exists=True
    )
    op.drop_index("ix_proposal_reviews_delegate_user_id", table_name="proposal_reviews", if_exists=True)
    op.drop_index("ix_proposal_reviews_user_id", table_name="proposal_reviews", if_exists=True)
    op.drop_index(
        "ix_profile_revisions_changed_by_user_id", table_name="profile_revisions", if_exists=True
    )
    op.drop_index(
        "ix_private_channel_members_added_by_user_id",
        table_name="private_channel_members",
        if_exists=True,
    )
    op.drop_index(
        "ix_private_channel_members_user_id", table_name="private_channel_members", if_exists=True
    )
    op.drop_index(
        "ix_email_notifications_agent_registry_id", table_name="email_notifications", if_exists=True
    )
    op.drop_index(
        "ix_email_notifications_thread_decision_id", table_name="email_notifications", if_exists=True
    )
    op.drop_index(
        "ix_delegate_invitations_accepted_by_user_id",
        table_name="delegate_invitations",
        if_exists=True,
    )
    op.drop_index(
        "ix_delegate_invitations_invited_by_user_id",
        table_name="delegate_invitations",
        if_exists=True,
    )
    op.drop_index("ix_cohorts_created_by", table_name="cohorts", if_exists=True)
    op.drop_index("ix_cohort_memberships_added_by", table_name="cohort_memberships", if_exists=True)
    op.drop_index("ix_cohort_audit_events_actor_id", table_name="cohort_audit_events", if_exists=True)
    op.drop_index("ix_agents_approved_by", table_name="agents", if_exists=True)
    op.drop_index("ix_agent_delegates_invitation_id", table_name="agent_delegates", if_exists=True)
    op.drop_index("ix_agent_delegates_user_id", table_name="agent_delegates", if_exists=True)
    op.drop_index("ix_access_allowlist_added_by_user_id", table_name="access_allowlist", if_exists=True)
