"""Static checks for #27 I4: upper caps on version-sensitive deps, plotly out
of the runtime install, an alembic floor high enough for `if_exists=` in
migration downgrades, and a lockfile that exists and names every runtime
dependency. Does not attempt to re-validate pip-compile's own hash pinning —
that's pip's job at install time (--require-hashes, wired in Task 27.6)."""

import os
import re
import shutil
import subprocess
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def _pyproject() -> dict:
    return tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())


def _dep_names(deps: list[str]) -> set[str]:
    return {re.split(r"[><=\[!~]", d, maxsplit=1)[0].strip() for d in deps}


def test_version_sensitive_deps_have_upper_caps():
    deps = {
        re.split(r"[><=\[!~]", d, maxsplit=1)[0].strip(): d
        for d in _pyproject()["project"]["dependencies"]
    }
    for name in ("fastapi", "sqlalchemy", "anthropic", "slack-sdk"):
        assert "<" in deps[name], f"{name} has no upper cap: {deps[name]!r}"


def test_plotly_is_a_scripts_extra_not_a_runtime_dependency():
    proj = _pyproject()["project"]
    assert "plotly" not in _dep_names(proj["dependencies"])
    assert any(d.startswith("plotly") for d in proj["optional-dependencies"]["scripts"])


def test_alembic_floor_supports_if_exists_downgrades():
    # alembic/versions/*.py downgrade() calls use if_exists= (op.drop_index,
    # op.drop_constraint, op.drop_column) which requires alembic>=1.16.
    deps = {
        re.split(r"[><=\[!~]", d, maxsplit=1)[0].strip(): d
        for d in _pyproject()["project"]["dependencies"]
    }
    alembic_spec = deps["alembic"]
    match = re.search(r">=\s*(\d+)\.(\d+)", alembic_spec)
    assert match, f"alembic has no >= floor: {alembic_spec!r}"
    major, minor = int(match.group(1)), int(match.group(2))
    assert (major, minor) >= (1, 16), f"alembic floor too low for if_exists=: {alembic_spec!r}"


def test_lockfile_exists_and_covers_every_runtime_dependency():
    lock_path = REPO_ROOT / "requirements.lock"
    assert lock_path.exists(), "requirements.lock is missing — run pip-compile"
    lock_text = lock_path.read_text()
    for name in _dep_names(_pyproject()["project"]["dependencies"]):
        # pip-compile may emit either the '-' or '_' spelling of a PEP 503
        # name (e.g. slack-sdk vs slack_sdk); accept both rather than
        # pinning to whichever one happened to come out of a given run. It
        # also preserves any requested extra in the pin itself (e.g.
        # `sqlalchemy[asyncio]==2.0.52`, `uvicorn[standard]==0.52.4`), so
        # tolerate an optional bracketed extras suffix before the `==`.
        escaped = re.escape(name).replace("\\-", "[-_]")
        pattern = rf"(?im)^{escaped}(\[[^\]]*\])?=="
        assert re.search(pattern, lock_text), f"{name} not pinned in requirements.lock"


def _ci_sh() -> str:
    return (REPO_ROOT / "scripts" / "ci.sh").read_text()


def test_ci_sh_fails_the_gate_when_the_lockfile_is_stale():
    text = _ci_sh()
    assert "piptools compile" in text
    assert "requirements.lock is stale" in text
    assert text.index("piptools compile") < text.index("-m pytest")


def test_ci_sh_lockcheck_has_a_documented_skip_valve():
    # #27 I4-e amendment: requirements.lock was cut against a throwaway Python 3.11.14
    # interpreter (Task 27.4), not $VENV_PY (3.12) — resolving with $VENV_PY here would
    # show spurious drift on every run for everyone. So the check must resolve with a
    # 3.11 interpreter and degrade to a SKIP (not a failure) when one isn't available.
    text = _ci_sh()
    assert "LOCKCHECK" in text
    assert "LOCKCHECK=none" in text
    assert "3.11" in text


def _strip_comment_lines(text: str) -> list[str]:
    """Mirrors scripts/ci.sh's `grep -v '^#'` used to compare lockfiles."""
    return [line for line in text.splitlines() if not line.startswith("#")]


def test_lockfile_comparison_ignores_pip_composes_own_header_but_not_real_pin_drift():
    # pip-compile's header records the --output-file path it was invoked with, so a raw
    # diff between the committed lock and a freshly regenerated scratch file can never
    # match even when every pin is byte-identical. scripts/ci.sh works around this by
    # diffing both sides with comment lines stripped first — verify that mechanism here
    # on synthetic fixtures, without shelling out to pip-compile at all.
    committed = (
        "#\n# This file is autogenerated by pip-compile\n"
        "#    --output-file=requirements.lock\n#\nfastapi==0.111.0\n"
    )
    regenerated_same_pins = (
        "#\n# This file is autogenerated by pip-compile\n"
        "#    --output-file=/tmp/scratch.abc123\n#\nfastapi==0.111.0\n"
    )
    regenerated_drifted = regenerated_same_pins.replace("0.111.0", "0.112.0")

    # Raw text differs (only the header's recorded path differs) even though the pins
    # agree — this is exactly why ci.sh never diffs the raw files directly.
    assert committed != regenerated_same_pins

    # Stripping comment lines makes the pins-only comparison agree when only the
    # header differs...
    assert _strip_comment_lines(committed) == _strip_comment_lines(regenerated_same_pins)
    # ...and still catches a real pin drift.
    assert _strip_comment_lines(committed) != _strip_comment_lines(regenerated_drifted)


def test_ci_sh_fails_the_gate_on_real_lockfile_drift(tmp_path):
    # Behavioural mutation check on ci.sh:376 (the stale-lock `exit 1`) — the static
    # test above only pins the substring; this actually runs scripts/ci.sh (same
    # shape test_run_migration_sh.py uses for bash) and proves it fails closed on a
    # REAL pip-compile resolution that disagrees with the committed lock.
    #
    # A symlink farm mirrors every top-level entry of the real repo except
    # pyproject.toml, which is a real copy with one dependency's cap lowered enough
    # that pip-compile must resolve an older pin than what is already committed in
    # (the symlinked, untouched) requirements.lock — never touches the real
    # pyproject.toml. ci.sh derives REPO_ROOT from its own invoked path
    # (`cd "$(dirname "${BASH_SOURCE[0]}")/.."`), so invoking the farm's symlinked
    # scripts/ci.sh makes REPO_ROOT resolve to tmp_path, and every relative
    # reference the script makes (alembic/, tests/, .venv-test/, requirements.lock,
    # pyproject.toml) resolves through the farm.
    if not shutil.which("uv"):
        import pytest

        pytest.skip("uv not on PATH — same skip valve ci.sh itself uses for this step")

    for entry in os.listdir(REPO_ROOT):
        if entry in (".git", "pyproject.toml"):
            continue
        (tmp_path / entry).symlink_to(REPO_ROOT / entry)

    original = (REPO_ROOT / "pyproject.toml").read_text()
    mutated = original.replace('"anthropic>=0.26.0,<1.0.0"', '"anthropic>=0.26.0,<0.100.0"')
    assert mutated != original, "mutation target line not found — pyproject.toml moved"
    (tmp_path / "pyproject.toml").write_text(mutated)

    proc = subprocess.run(
        ["./scripts/ci.sh"],
        cwd=tmp_path,
        env={**os.environ, "CI_MIGRATION_DB": "none"},
        capture_output=True,
        text=True,
        timeout=180,
    )
    assert proc.returncode != 0, proc.stdout + proc.stderr
    assert "requirements.lock is stale" in proc.stdout + proc.stderr
    assert "==> mypy" not in proc.stdout, "gate must stop at the lockfile check, not reach mypy"


def test_lock_smoke_step_is_documented_and_opt_in():
    # #27 I6: the freshness gate above proves the lock MATCHES pyproject.toml;
    # nothing proves it actually WORKS on the Python 3.11 the Dockerfile installs
    # it on. Static pin that the opt-in smoke step exists, is off by default, and
    # names the three entry points it imports.
    text = _ci_sh()
    assert "LOCK_SMOKE" in text
    assert re.search(r'LOCK_SMOKE:-\}"\s*!=\s*"1"', text) or '"${LOCK_SMOKE:-}" != "1"' in text
    for module in ("src.main", "src.worker.main", "src.agent.main"):
        assert module in text, f"lock smoke step does not mention {module!r}"
    assert "--require-hashes" in text


def test_lock_smoke_step_defaults_to_a_visible_skip():
    # Behavioural: with LOCK_SMOKE unset (the default), the step must print its
    # one-line skip note rather than silently doing nothing — cheap to check since
    # the step's own default path costs nothing (it's an early bash `if`, no venv
    # created). Piggybacks on MYPY_MAX=0 to stop the gate quickly afterwards,
    # same shape as test_ci_gate.py's mypy behavioural tests.
    proc = subprocess.run(
        ["./scripts/ci.sh"],
        cwd=REPO_ROOT,
        # LOCK_SMOKE must be scrubbed, not merely left unset: this test asserts the
        # DEFAULT behaviour, and inheriting an ambient LOCK_SMOKE=1 from the operator's
        # own shell would make the step run for real and fail this assertion (which is
        # exactly what happened on a `LOCK_SMOKE=1 ./scripts/ci.sh` gate run).
        env={
            k: v for k, v in os.environ.items() if k != "LOCK_SMOKE"
        } | {"CI_MIGRATION_DB": "none", "LOCKCHECK": "none", "MYPY_MAX": "0"},
        capture_output=True,
        text=True,
        timeout=180,
    )
    assert "==> lock smoke test" in proc.stdout
    assert "skipped (opt-in" in proc.stdout
    assert proc.returncode != 0, proc.stdout + proc.stderr
